name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: all_tests
        type: choice
        options:
          - test_authorization
          - test_settings
          - test_vocabulary
          - all_tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests for test_authorization
        if: "github.event.inputs.deployment_target == 'test_authorization'"
        run: pytest -sv tests/test_authorization/* --disable-warnings
        continue-on-error: true

      - name: Run tests for test_settings
        if: "github.event.inputs.deployment_target == 'test_settings'"
        run: pytest -sv tests/test_settings/test_settings.py --disable-warnings
        continue-on-error: true

      - name: Run tests for test_vocabulary
        if: "github.event.inputs.deployment_target == 'test_vocabulary'"
        run: pytest -sv tests/test_settings/test_vocabulary.py --disable-warnings
        continue-on-error: true

      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all_tests'"
        run: pytest -sv tests/* --disable-warnings
        continue-on-error: true

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.run_id }}
          path: results
          retention-days: 1