name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: test_authorization
        type: choice
        options:
          - test_authorization
          - test_settings
          - test_vocabulary

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test_authorization
        if: "github.event.inputs.deployment_target == 'test_authorization'"
        run: pytest tests/test_authorization
      - name: test_settings
        if: "github.event.inputs.deployment_target == 'test_settings'"
        run: pytest tests/test_settings/test_settings.py
      - name: test_vocabulary
        if: "github.event.inputs.deployment_target == 'test_vocabulary'"
        run: pytest tests/test_settings/test_vocabulary.py